apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
spec:
  replicas: 10
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
        hello: world
    spec:
      containers:
        - image: httpd:alpine3.18
          name: httpd
  strategy:
    type: 
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
