apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      meta.helm.sh/release-name: homarr
      meta.helm.sh/release-namespace: homarr
    creationTimestamp: "2024-10-06T23:51:23Z"
    generation: 1
    labels:
      app.kubernetes.io/instance: homarr
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: homarr
      app.kubernetes.io/version: 0.15.4
      helm.sh/chart: homarr-1.2.6
    name: homarr
    namespace: homarr
    resourceVersion: "76687"
    uid: 8ca57bb1-9cf4-463b-9fdd-24c711c79da2
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app.kubernetes.io/instance: homarr
        app.kubernetes.io/name: homarr
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app.kubernetes.io/instance: homarr
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/name: homarr
          app.kubernetes.io/version: 0.15.4
          helm.sh/chart: homarr-1.2.6
      spec:
        containers:
        - env:
          - name: AUTH_LDAP_ADMIN_GROUP
            value: admin
          - name: AUTH_LDAP_BASE
          - name: AUTH_LDAP_BIND_DN
          - name: AUTH_LDAP_GROUP_CLASS
            value: groupOfUniqueNames
          - name: AUTH_LDAP_GROUP_MEMBER_ATTRIBUTE
            value: member
          - name: AUTH_LDAP_GROUP_MEMBER_USER_ATTRIBUTE
            value: dn
          - name: AUTH_LDAP_OWNER_GROUP
            value: admin
          - name: AUTH_LDAP_SEARCH_SCOPE
            value: base
          - name: AUTH_LDAP_URI
          - name: AUTH_LDAP_USERNAME_ATTRIBUTE
            value: uid
          - name: AUTH_OIDC_ADMIN_GROUP
            value: admin
          - name: AUTH_OIDC_CLIENT_NAME
            value: OIDC
          - name: AUTH_OIDC_OWNER_GROUP
            value: admin
          - name: AUTH_OIDC_SCOPE_OVERWRITE
            value: openid email profile groups
          - name: AUTH_OIDC_URI
          - name: AUTH_PROVIDER
            value: credentials
          - name: DEFAULT_COLOR_SCHEME
            value: dark
          - name: TZ
            value: Europe/Paris
          image: ghcr.io/ajnart/homarr:0.15.4
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: homarr
          ports:
          - containerPort: 7575
            name: http
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          securityContext: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2024-10-06T23:51:35Z"
      lastUpdateTime: "2024-10-06T23:51:35Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2024-10-06T23:51:23Z"
      lastUpdateTime: "2024-10-06T23:51:35Z"
      message: ReplicaSet "homarr-5474d8f6bf" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
