apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: homarr
    meta.helm.sh/release-namespace: homarr
  creationTimestamp: "2024-10-06T23:51:23Z"
  labels:
    app.kubernetes.io/instance: homarr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: homarr
    app.kubernetes.io/version: 0.15.4
    helm.sh/chart: homarr-1.2.6
  name: homarr
  namespace: homarr
  resourceVersion: "76653"
  uid: ae3794db-a5df-47ac-b209-ea6e494d43da
spec:
  clusterIP: 10.43.114.58
  clusterIPs:
  - 10.43.114.58
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 7575
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: homarr
    app.kubernetes.io/name: homarr
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
